spring:
  datasource:
    hikari:
      maxLifetime: 1800000 # 30 minutes (adjust this value as needed)
    url: jdbc:postgresql://dpg-ck45e936fquc73cithig-a:5432/landlord_vdbh
    username: landlord_vdbh_user
    password: NjuwXosM8H4TnII1cajGXzydrdQTnqun
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always


#spring:
#  datasource:
#    url: jdbc:postgresql://ec2-54-84-182-168.compute-1.amazonaws.com:5432/drcoojidn826q
#    username: jkfxbqtagncspk
#    password: e6cf7f23cebaa964c00cd2499c7fb15da7388b13df2c808871bb0b8a51cf3380
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#
## TO GET A MESSAGE FROM OUR EXCEPTION
#server:
#  error:
#    include-message: always
#
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#.;

#  server:
#
#    port:8080
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/landlord
#    username: postgres
#    password: 123
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#
## TO GET A MESSAGE FROM OUR EXCEPTION
#server:
#  error:
#    include-message: always
#
##
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

#
#  server:
#    port:8080
#
#  spring:
#    datasource:
#      url: jdbc:mysql://containers-us-west-189.railway.app:7848/railway
#      username: root
#      password: 9AXX6Z5n2DFstBlva3fa
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#  #      update
#  #

#server:
#  port:8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://containers-us-west-189.railway.app:7848/railway
#    username: root
#    password: 9AXX6Z5n2DFstBlva3fa
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      update
#



#server:
#  port:8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/landlord
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
##      update
##      create-drop